### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yukachilov** [yukachilov/chat-space#12]
IPアドレス
18.176.137.126

**Comment by kohei-isoda** [comment]
安部さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ 同期通信 / 非同期通信でcssに相違がある
[![Screenshot from Gyazo](https://gyazo.com/42935a6902e482043bb7d023af9b39cd/raw)](https://gyazo.com/42935a6902e482043bb7d023af9b39cd)
`※ 画像上が同期通信、下が非同期通信です。上が正しいcss（見本）になりますので合わせていただければと思います！`

◯ メンバー欄にあるユーザー同士の間にカンマやスペースが無いので見づらい
[![Screenshot from Gyazo](https://gyazo.com/8fd43c92bf239a548edd15466dbfdf4f/raw)](https://gyazo.com/8fd43c92bf239a548edd15466dbfdf4f)

◯ テキスト+画像で送信した際に（見本と比べ）cssが崩れている
[![Screenshot from Gyazo](https://gyazo.com/b3010cfd3925e6cd48d82dd4941c469e/raw)](https://gyazo.com/b3010cfd3925e6cd48d82dd4941c469e)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yukachilov** [comment]
修正しました

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①ユーザー名とグループ情報の縦ラインが揃っていない
②ボタンの色が見本と異なる

③メンバーの名前の間にスペースがない
[![Image from Gyazo](https://i.gyazo.com/daa23412cb84d093698a2a4528e6bed0.png)](https://gyazo.com/daa23412cb84d093698a2a4528e6bed0)

④メッセージの表示形式が見本と異なる
[![Image from Gyazo](https://i.gyazo.com/127f5906df7eb9effe6657b1c0645b64.png)](https://gyazo.com/127f5906df7eb9effe6657b1c0645b64)

※カリキュラムの中にある、模範のchatspaceと仕様書を参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/
[仕様書]
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yukachilov** [comment]
修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
再度確認したところ、全ての項目の修正が確認できませんでした。
（メッセージの表示については、リロードすると正しい表記になりますが、投稿した直後は以前の表示のままです）

デプロイはお済みでしょうか？
デプロイがうまくできていない場合もありますので、ご確認をお願い致します！
本番環境にて、修正が確認できましたら再度下記のフォームの投稿をお願い致します。
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yukachilov** [comment]
再度デプロイして本番で確認しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
